export const panelTypes = [
  {
    id: 'text-note',
    name: '텍스트 노트',
    description: '간단한 텍스트 메모를 작성할 수 있는 패널입니다.',
    icon: 'note',
    type: 'TextNoteNexaPanel',
  },
  {
    id: 'image-viewer',
    name: '이미지 뷰어',
    description: '이미지를 표시하고 관리할 수 있는 패널입니다.',
    icon: 'image',
    type: 'ImageViewerNexaPanel',
  },
  {
    id: 'sample-chart',
    name: '샘플 차트',
    description: '데이터를 시각화하는 차트 패널입니다.',
    icon: 'show_chart',
    type: 'SampleChartNexaPanel',
  },
  {
    id: 'device-status',
    name: '디바이스 상태',
    description: '연결된 디바이스의 상태를 모니터링하는 패널입니다.',
    icon: 'devices',
    type: 'DeviceStatusNexaPanel',
  },
  {
    id: 'simple-text-display',
    name: '텍스트 디스플레이',
    description: '단순 텍스트 정보를 표시하는 패널입니다.',
    icon: 'text_fields',
    type: 'SimpleTextDisplayNexaPanel',
  },
  {
    id: 'gauge',
    name: '게이지',
    description: '수치를 게이지 형태로 표시하는 패널입니다.',
    icon: 'speed',
    type: 'GaugeNexaPanel',
  },
  {
    id: 'boolean-indicator',
    name: '상태 표시기',
    description: '켜짐/꺼짐 상태를 표시하는 패널입니다.',
    icon: 'toggle_on',
    type: 'BooleanIndicatorNexaPanel',
  },
  {
    id: 'log-viewer',
    name: '로그 뷰어',
    description: '시스템 로그를 확인하는 패널입니다.',
    icon: 'list_alt',
    type: 'LogViewerNexaPanel',
  },
  {
    id: 'button-control',
    name: '버튼 제어',
    description: '디바이스를 제어하는 버튼 패널입니다.',
    icon: 'smart_button',
    type: 'ButtonControlNexaPanel',
  },
  {
    id: 'switch-control',
    name: '스위치 제어',
    description: '디바이스를 켜고 끄는 스위치 패널입니다.',
    icon: 'power_settings_new',
    type: 'SwitchControlNexaPanel',
  },
  {
    id: 'slider-control',
    name: '슬라이더 제어',
    description: '값을 조절하는 슬라이더 패널입니다.',
    icon: 'linear_scale',
    type: 'SliderControlNexaPanel',
  },
  {
    id: 'input-command',
    name: '명령어 입력',
    description: '명령어를 입력하는 패널입니다.',
    icon: 'keyboard',
    type: 'InputCommandNexaPanel',
  },
  {
    id: 'color-picker-control',
    name: '색상 선택',
    description: '색상을 선택하는 패널입니다.',
    icon: 'palette',
    type: 'ColorPickerControlNexaPanel',
  },
  {
    id: 'automation-rule-editor',
    name: '자동화 규칙',
    description: '자동화 규칙을 편집하는 패널입니다.',
    icon: 'auto_fix_high',
    type: 'AutomationRuleEditorNexaPanel',
  },
  {
    id: 'notification-center',
    name: '알림 센터',
    description: '시스템 알림을 확인하는 패널입니다.',
    icon: 'notifications',
    type: 'NotificationCenterNexaPanel',
  },
]
