; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = arduino
upload_protocol = esptool

; 보드 상세 설정
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L

; 시리얼 통신 설정
monitor_speed = 115200
upload_speed = 115200
monitor_port = COM6
monitor_filters = direct
monitor_echo = yes
monitor_eol = LF

; OTA 업로드 설정 (나중에 활성화)
; upload_protocol = espota
; upload_port = 192.168.0.100  ; ESP32-C3의 IP 주소로 변경해주세요
