# NEXA 플랫폼 배포 매뉴얼 (이 파일은 개발 환경에서 도커 컨테이너를 실행하는 명령어 파일)
# ------------------------------------------
# 0. 폴더이동: cd nexa-platform  (docker-dev-compose.yml 파일이 있는 폴더로 이동)
# 1. 실행: docker compose -f docker-dev-compose.yml up -d
# 2. 중지: docker compose -f docker-dev-compose.yml down
# 3. 로그 확인: docker compose -f docker-dev-compose.yml logs -f
# ==========================================
services:
  nexa-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-nexa-web
    ports:
      - '9000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - MYSQL_HOST=192.168.0.15
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=nexa_db
      - MYSQL_PORT=3306
      - NODE_ENV=development
    restart: always

  dev-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: dev-cloudflared-tunnel
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiYTZlODYwNDljYTdkMDM3MGY0NjVmYmNlY2VmYzc1MzAiLCJ0IjoiZTU4ZDk1ZGYtNzQ3NC00YTlkLTlkYjgtN2NkOThmZDJhMWRlIiwicyI6IlkyWm1OVGt5WWpZdE5ESTFNaTAwWVRreUxUbGlNbU10WW1VNE5UZGtaV1JpTXpVMSJ9
