esphome:
  name: device-name-1  # 파일명과 가급적 일치시키는 것이 좋습니다.
  friendly_name: 거실 조명

esp32: # 사용하시는 보드가 ESP32인지 ESP8266인지 명시
  board: esp32dev

# 무선 업데이트 및 관리용 (비워두면 대시보드에서 경고가 날 수 있음)
api:
  encryption:
    key: "보안키값" # 대시보드에서 생성해준 값을 쓰는 게 좋습니다.

ota: # 이게 있어야 나중에 무선으로 코드를 보낼 수 있습니다.
  - platform: esphome
